name: Integration test

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref-branch:
        required: false
        type: string
        default: ''

jobs:
  go-echarts-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.18'

      - name: Checkout Example branch
        run: |
          echo "Checkout Example branch is: ${{ inputs.ref-branch }}, empty means default branch "

      - name: Checkout another repository
        uses: actions/checkout@v5
        with:
          repository: 'go-echarts/examples'
          ref: ${{ inputs.ref-branch }}
          path: 'examples'

      - name: Check repos
        run: |
          echo "Main repo ==>"
          ls -l
          echo "Example repo ==>"
          ls examples/

      - name: Remove renderer files out of test scope
        working-directory: ./examples
        run: |
          rm -rf examples/renderer.go
      

      - name: Run Examples generate original html files based on master branch
        working-directory: ./examples
        run: |
          echo "Currently working on go-echarts version ===>"
          echo "replace github.com/go-echarts/go-echarts/v2 => github.com/go-echarts/go-echarts/v2 master" >> go.mod
          cat go.mod
          go mod tidy
          cat go.mod
          go run . false

      - name: Check Examples generate html files and mv as snapshot
        working-directory: ./examples
        run: |
          ls examples/html/
          mkdir -p examples/snapshot
          mv examples/html/*.html examples/snapshot/
          ls examples/snapshot/

      - name: Replace dependency as local
        working-directory: ./examples
        run: |
          sed -i '/replace/d' go.mod
          cat go.mod
          echo "replace github.com/go-echarts/go-echarts/v2 => ../../go-echarts" >> go.mod

      - name: Check Examples changed files
        working-directory: ./examples
        run: |
          cat go.mod

      - name: Run Examples generate html files
        working-directory: ./examples
        run: |
          go mod tidy
          go run . false

      - name: Check all Examples snapshot and generate html files done
        id: check-generated-size
        run: |
          echo "Currently  examples/examples/snapshot/ html files size ===>"
          echo $(find examples/examples/snapshot/ -type f -name "*.html" | wc -l)
          echo "SNAPSHOT_FILE_SIZE=$(find examples/examples/snapshot/ -type f -name "*.html" | wc -l)" >> $GITHUB_OUTPUT
          echo "Currently  examples/examples/html/ html files size ===>"
          echo $(find examples/examples/html/ -type f -name "*.html" | wc -l)
          echo "GENERATED_FILE_SIZE=$(find examples/examples/html/ -type f -name "*.html" | wc -l)" >> $GITHUB_OUTPUT
          echo "Currently  examples/examples/snapshot/ html details ===>"
          ls examples/examples/snapshot/
          echo "Currently  examples/examples/html/ html details ===>"
          ls examples/examples/html/

      - name: Compare generated file counts mismatch
        if: ${{ steps.check-generated-size.outputs.SNAPSHOT_FILE_SIZE != steps.check-generated-size.outputs.GENERATED_FILE_SIZE }}
        run: |
          echo ${{ steps.check-generated-size.outputs.SNAPSHOT_FILE_SIZE }}
          echo ${{ steps.check-generated-size.outputs.GENERATED_FILE_SIZE }}
          echo "Error: Generated HTML File counts are different! Please check!"
          exit 1

      - name: Checkout integration pipeline repository
        uses: actions/checkout@v5
        with:
          repository: 'go-echarts/go-echarts-pipeline'
          path: 'go-echarts-pipeline'

      - name: Start compare files contents
        run: |
          mv examples/examples/snapshot ./go-echarts-pipeline/
          mv examples/examples/html ./go-echarts-pipeline/
          cd go-echarts-pipeline
          ls
          python integration.py
